Models/Flavor.cs
using System.Collections.Generic;

namespace Treats.Models
{
  public class Flavor
  {
    public Flavor()

        {
            this.TreatFlavors = new HashSet<TreatFlavor>();
        }
    public int FlavorId { get; set; }
    public string FlavorType { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<TreatFlavor> TreatFlavors { get; set;}
  }
}

Controllers/FlavorController.cs
using Microsoft.AspNetCore.Mvc;
using Treats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Treats.Controllers
{
   
  public class FlavorController : Controller
  {
    private readonly TreatsContext _db;
    
   public FlavorController(TreatsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavor.ToList();
      return View(model);
    }
    [Authorize]
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavor.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpGet("/flavor/info/{id}")]
    public ActionResult Info(int id)
    {
        var thisFlavor = _db.Flavor
        .Include(flavor => flavor.AllTreats)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
        return View(thisFlavor);
    }
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavor.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }
    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
     public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavor.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavor.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavor.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Controllers/TreatController.cs
using Microsoft.AspNetCore.Mvc;
using Treats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Treats.Controllers
{
   
  public class TreatController : Controller
  {
    private readonly TreatsContext _db;
    
    public TreatController(TreatsContext db)
    {
      _db = db;
    }
    
    public ActionResult Index()
    {
      List<Treat> model = _db.Treat.ToList();
      return View(model);
    }
  [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treat.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Info(int id)
    {
        var thisTreat = _db.Treat
        .Include(treat => treat.Flavors)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
        return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treat.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treat.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treat.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treat.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Views/Flavor/AddTreat.cshtml
@model Treats.Models.Flavor

<h2>Add a Treat selection</h2>

<h4>Add a Treat type: @Html.DisplayFor(model => model.FlavorType)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select Treat Type")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Flavors", "Index")</p>

Views/Flavor/Create.cshtml
@model Treats.Models.Flavor

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
    @Html.Label("Flavor Type:")
    @Html.TextBoxFor(model => model.FlavorType)

    <input type="submit" value="Add new item" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

Views/Flavor/Delete.cshtml
@model Treats.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.FlavorType): @Html.DisplayFor(model => model.FlavorType)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Flavors", "Index")

Views/Flavor/Edit.cshtml
@model Treats.Models.Flavor

<h2>Edit</h2>

<h4>Edit this Flavor: @Html.DisplayFor(model => model.FlavorType)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.FlavorType)
    @Html.EditorFor(model => model.FlavorType)
    <hr/>

    @Html.Label("Select Treat")
    @Html.DropDownList("TreatId")
    <hr/>

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Flavors", "Index")</p>

Views/Flavor/Index.cshtml
@using Treats.Models;
@model IEnumerable<Treats.Models.Flavor>;

<h1>Flavors for @User.Identity.Name</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.FlavorType}", "Info", new { id = flavor.FlavorId })</li>
    }
  </ul>
} 
else
{
  <h3>No flavors have been added yet!</h3>
}

<p>@Html.ActionLink("Add a new flavor", "Create")</p>
<p>@Html.ActionLink("See all Treat Selections", "Index", "Treat")</p>
<p>@Html.ActionLink("Got to Homepage", "Index", "Home")</p>

Views/Flavor/Info.cshtml
<!-- Flavor -->
@using Treats.Models;
@model Treats.Models.Flavor;

<h2>Flavors</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.FlavorType):
  @Html.DisplayFor(model => model.FlavorType)</h3>

@if(@Model.Treats.Count > 0)
{
  <h4>Treats with this flavor:</h4>
  <ul>
  @foreach(var join in Model.AllTreats)
  {
    <li>@join.Treat.Type</li>
     @using (Html.BeginForm("DeleteTreat", "Flavor"))
    {
      @Html.Hidden("joinId", @join.TreatFlavorId)
      //arguments- variable to pass through and the actual value of that parameter
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
  
}
else
{
  <p>There are no treats with this flavor</p>
}
<p>@Html.ActionLink("Back to Flavors", "Index")</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Add a Treat Selection", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("See all Treat Selections", "Index", "Treat")</p>
<p>@Html.ActionLink("Back to Homepage", "Index", "Home")</p>